import type { GraphState } from './graph.types';

export const mockGraphState: GraphState = {
  graph_id: 'graph_hochwab_001',
  boundary_id: 'bnd_hochwab_nord_001',
  extraction_id: 'ext_001',
  nodes: [
    {
      node_id: 'n_001',
      geometry: { type: 'Point', coordinates: [15.21, 47.64] },
      node_type: 'poi_anchor',
      elevation_meters: 1210,
      connected_edge_ids: ['e_001', 'e_002'],
      poi_id: 'poi_001',
    },
    {
      node_id: 'n_002',
      geometry: { type: 'Point', coordinates: [15.18, 47.63] },
      node_type: 'trailhead',
      elevation_meters: 980,
      connected_edge_ids: ['e_001'],
    },
    {
      node_id: 'n_003',
      geometry: { type: 'Point', coordinates: [15.23, 47.66] },
      node_type: 'junction',
      elevation_meters: 1350,
      connected_edge_ids: ['e_002', 'e_003'],
    },
    {
      node_id: 'n_004',
      geometry: { type: 'Point', coordinates: [15.25, 47.67] },
      node_type: 'elevation_peak',
      elevation_meters: 1520,
      connected_edge_ids: ['e_003'],
    },
  ],
  edges: [
    {
      edge_id: 'e_001',
      from_node_id: 'n_002',
      to_node_id: 'n_001',
      geometry: { type: 'LineString', coordinates: [[15.18, 47.63], [15.21, 47.64]] },
      length_meters: 2800,
      edge_type: 'trail',
      difficulty_class: 'moderate',
      bidirectional: true,
    },
    {
      edge_id: 'e_002',
      from_node_id: 'n_001',
      to_node_id: 'n_003',
      geometry: { type: 'LineString', coordinates: [[15.21, 47.64], [15.23, 47.66]] },
      length_meters: 1900,
      edge_type: 'trail',
      difficulty_class: 'moderate',
      bidirectional: true,
    },
    {
      edge_id: 'e_003',
      from_node_id: 'n_003',
      to_node_id: 'n_004',
      geometry: { type: 'LineString', coordinates: [[15.23, 47.66], [15.25, 47.67]] },
      length_meters: 1200,
      edge_type: 'trail',
      difficulty_class: 'difficult',
      bidirectional: true,
    },
  ],
  metrics: {
    node_count: 4,
    edge_count: 3,
    total_length_meters: 5900,
    connected_components: 1,
    poi_anchor_count: 1,
    coverage_ratio: 0.72,
  },
  validation: {
    is_valid: true,
    errors: [],
    warnings: [],
    checked_at: '2026-05-21T00:03:00.000Z',
    checked_against_boundary_id: 'bnd_hochwab_nord_001',
    checked_against_extraction_id: 'ext_001',
  },
  status: 'graph_valid',
  built_at: '2026-05-21T00:03:00.000Z',
};
