import type { RegioContentState } from './regioContent.types';

export const mockRegioContentState: RegioContentState = {
  regio_content_version: 'regio_v1.0.0',
  source: 'mock',
  loaded_at: '2026-05-21T00:00:00.000Z',
  region: {
    region_id: 'region_hochwab_nord',
    region_name: 'Hochschwab Nord',
    region_type: 'trail_area',
    country_code: 'AT',
    default_language: 'de',
    timezone: 'Europe/Vienna',
    bbox: [15.0, 47.5, 15.4, 47.8],
  },
  approved_pois: [
    {
      poi_id: 'poi_001',
      source_poi_id: 'osm_node_123',
      source: 'osm',
      name: 'Beispielhütte',
      category: 'alpine_hut',
      candidate_class: 'safe_relevant',
      status: 'approved',
      center: { type: 'Point', coordinates: [15.21, 47.64] },
      radius_meters: 50,
      comparison_margin_meters: 25,
      effective_comparison_radius_meters: 75,
      visibility: 'scim_active',
      approved_by: 'operator_mock',
      approved_at: '2026-05-21T00:00:00.000Z',
      system_adjust_version: 'sys_v1.0.0',
    },
  ],
  rejected_pois: [
    {
      poi_id: 'poi_rejected_001',
      source_poi_id: 'osm_node_456',
      source: 'osm',
      name: 'Nicht relevanter Wegweiser',
      category: 'information',
      center: { type: 'Point', coordinates: [15.23, 47.65] },
      rejected_reason: 'not_stay_relevant',
      rejected_by: 'operator_mock',
      rejected_at: '2026-05-21T00:00:00.000Z',
    },
  ],
  pending_pois: [
    {
      poi_id: 'poi_pending_001',
      source_poi_id: 'osm_node_789',
      source: 'osm',
      name: 'Aussichtspunkt zur Prüfung',
      category: 'viewpoint',
      candidate_class: 'safe_relevant',
      center: { type: 'Point', coordinates: [15.25, 47.66] },
      suggested_radius_meters: 35,
      suggested_comparison_margin_meters: 25,
      review_reason: 'Operator-Freigabe ausstehend',
      created_at: '2026-05-21T00:00:00.000Z',
    },
  ],
  poi_radii: [
    {
      poi_id: 'poi_001',
      radius_meters: 50,
      radius_source: 'operator_adjusted',
      radius_status: 'confirmed',
      comparison_margin_meters: 25,
      effective_comparison_radius_meters: 75,
      min_allowed_radius_meters: 5,
      max_allowed_radius_meters: 500,
      system_adjust_version: 'sys_v1.0.0',
      updated_by: 'operator_mock',
      updated_at: '2026-05-21T00:00:00.000Z',
    },
  ],
  regional_parameters: {
    parameter_version: 'regio_params_v1.0.0',
    comparison_margin_meters: 25,
    stay_density_ratio: 1.6,
    movement_load_threshold: 0.7,
    stay_load_threshold: 0.7,
    route_degrade_threshold: 0.65,
    route_exclude_threshold: 0.9,
    route_exceedance_behavior: 'degrade',
    signal_validity_seconds: 300,
    aggregation_window_seconds: 300,
    smoothing_strength: 0.35,
    edge_weight_factor: 1.0,
    fallback_route_policy: 'allow_degraded_if_no_alternative',
    route_profiles: [
      {
        profile_id: 'low_load_route',
        label: 'Auslastungsarme Route',
        movement_load_threshold: 0.55,
        stay_load_threshold: 0.55,
        route_degrade_threshold: 0.5,
        route_exclude_threshold: 0.85,
        route_exceedance_behavior: 'profile_dependent',
        enabled: true,
      },
    ],
    system_adjust_version: 'sys_v1.0.0',
  },
  regional_restrictions: [
    {
      restriction_id: 'restriction_001',
      type: 'seasonal_closure',
      geometry: {
        type: 'LineString',
        coordinates: [
          [15.20, 47.63],
          [15.22, 47.64],
        ],
      },
      label: 'Saisonale Sperre Beispielweg',
      severity: 'medium',
      route_effect: 'degrade',
      display_effect: 'sensus_core_warning',
      valid_from: '2026-05-01T00:00:00.000Z',
      valid_until: '2026-10-31T23:59:59.000Z',
      source: 'operator',
      status: 'approved',
      approved_by: 'operator_mock',
      approved_at: '2026-05-21T00:00:00.000Z',
    },
  ],
  regional_warnings: [],
  release: {
    release_status: 'released',
    release_id: 'regio_release_001',
    released_by: 'operator_mock',
    released_at: '2026-05-21T00:00:00.000Z',
    changelog: 'Initialer Mock-Release für Panel 2.',
    blocks_runtime_use: false,
  },
  validation: {
    is_valid: true,
    errors: [],
    warnings: [],
    checked_at: '2026-05-21T00:00:00.000Z',
    checked_against_system_adjust_version: 'sys_v1.0.0',
  },
  status: 'regio_content_valid',
};
