import type { RegioContentState } from './regioContent.types';

// Generiert aus data/grunberg_pois.json (31 POIs, Stand 2026-05-25).
// Quelle: OSM Overpass mit Polygon-Filter + Querprüfung gegen
// gruenberg.info-Empfehlungen. Default-Inhalt für P02 während der
// MVP-Grünberg-Phase. Tests verwenden weiterhin den Mock.
//
// operator_note kodiert das Operator-Icon-Label und falls vorhanden
// einen Subtyp, z.B. "icon: Hochschaubahn | label: Sommerrodeln | subtype: alpine_coaster".
// Der spätere Icon-Mapper (T-?) liest diese Marker.

export const grunbergRegioContentState: RegioContentState = {
  regio_content_version: 'regio_v1.0.0',
  source: 'local_json',
  loaded_at: '2026-05-25T00:00:00.000Z',
  region: {
    region_id: 'region_gruenberg',
    region_name: 'Grünberg',
    region_type: 'trail_area',
    country_code: 'AT',
    default_language: 'de',
    timezone: 'Europe/Vienna',
    bbox: [13.801918, 47.869611, 13.864059, 47.922784],
  },
  approved_pois: [
    {
      poi_id: "poi_001",
      source_poi_id: "way/48231263#start",
      source: "osm",
      name: "Grünbergseilbahn Talstation",
      category: "aerialway_station",
      candidate_class: "safe_relevant",
      status: "approved",
      center: { type: "Point", coordinates: [13.8080206, 47.9133908] },
      radius_meters: 40,
      comparison_margin_meters: 25,
      effective_comparison_radius_meters: 65,
      visibility: "scim_active",
      operator_note: "icon: Seilbahn-Tal | label: Talstation",
      approved_by: "osm_extract_2026-05-25",
      approved_at: "2026-05-25T00:00:00.000Z",
      system_adjust_version: "sys_v1.0.0",
    },
    {
      poi_id: "poi_002",
      source_poi_id: "way/48231263#end",
      source: "osm",
      name: "Grünbergseilbahn Bergstation",
      category: "aerialway_station",
      candidate_class: "safe_relevant",
      status: "approved",
      center: { type: "Point", coordinates: [13.8215572, 47.8983187] },
      radius_meters: 40,
      comparison_margin_meters: 25,
      effective_comparison_radius_meters: 65,
      visibility: "scim_active",
      operator_note: "icon: Seilbahn-Berg | label: Bergstation",
      approved_by: "osm_extract_2026-05-25",
      approved_at: "2026-05-25T00:00:00.000Z",
      system_adjust_version: "sys_v1.0.0",
    },
    {
      poi_id: "poi_003",
      source_poi_id: "node/4211014216",
      source: "osm",
      name: "Landhotel Grünberg",
      category: "manual_other",
      candidate_class: "safe_relevant",
      status: "approved",
      center: { type: "Point", coordinates: [13.8062404, 47.9038508] },
      radius_meters: 25,
      comparison_margin_meters: 25,
      effective_comparison_radius_meters: 50,
      visibility: "scim_active",
      operator_note: "icon: Hotel | label: Landhotel | subtype: hotel",
      approved_by: "osm_extract_2026-05-25",
      approved_at: "2026-05-25T00:00:00.000Z",
      system_adjust_version: "sys_v1.0.0",
    },
    {
      poi_id: "poi_004",
      source_poi_id: "node/8071030647",
      source: "osm",
      name: "Franzl im Holz",
      category: "restaurant",
      candidate_class: "safe_relevant",
      status: "approved",
      center: { type: "Point", coordinates: [13.8442781, 47.9044099] },
      radius_meters: 25,
      comparison_margin_meters: 25,
      effective_comparison_radius_meters: 50,
      visibility: "scim_active",
      operator_note: "icon: Gasthaus | label: Franzl im Holz",
      approved_by: "osm_extract_2026-05-25",
      approved_at: "2026-05-25T00:00:00.000Z",
      system_adjust_version: "sys_v1.0.0",
    },
    {
      poi_id: "poi_005",
      source_poi_id: "way/191354192",
      source: "osm",
      name: "Gasthaus zum Silberfuchs",
      category: "restaurant",
      candidate_class: "safe_relevant",
      status: "approved",
      center: { type: "Point", coordinates: [13.8434734, 47.9040582] },
      radius_meters: 25,
      comparison_margin_meters: 25,
      effective_comparison_radius_meters: 50,
      visibility: "scim_active",
      operator_note: "icon: Gasthaus | label: Silberfuchs",
      approved_by: "osm_extract_2026-05-25",
      approved_at: "2026-05-25T00:00:00.000Z",
      system_adjust_version: "sys_v1.0.0",
    },
    {
      poi_id: "poi_006",
      source_poi_id: "way/189655256",
      source: "osm",
      name: "Hois'n Wirt am Traunsee",
      category: "restaurant",
      candidate_class: "safe_relevant",
      status: "approved",
      center: { type: "Point", coordinates: [13.8115258, 47.8808288] },
      radius_meters: 25,
      comparison_margin_meters: 25,
      effective_comparison_radius_meters: 50,
      visibility: "scim_active",
      operator_note: "icon: Restaurant | label: Hois'n",
      approved_by: "osm_extract_2026-05-25",
      approved_at: "2026-05-25T00:00:00.000Z",
      system_adjust_version: "sys_v1.0.0",
    },
    {
      poi_id: "poi_007",
      source_poi_id: "node/1350658253",
      source: "osm",
      name: "Ramsaualm am Laudachsee",
      category: "restaurant",
      candidate_class: "safe_relevant",
      status: "approved",
      center: { type: "Point", coordinates: [13.8498753, 47.8806194] },
      radius_meters: 25,
      comparison_margin_meters: 25,
      effective_comparison_radius_meters: 50,
      visibility: "scim_active",
      operator_note: "icon: Gasthaus | label: Ramsaualm",
      approved_by: "osm_extract_2026-05-25",
      approved_at: "2026-05-25T00:00:00.000Z",
      system_adjust_version: "sys_v1.0.0",
    },
    {
      poi_id: "poi_008",
      source_poi_id: "way/191354191",
      source: "osm",
      name: "Grünbergalm",
      category: "restaurant",
      candidate_class: "safe_relevant",
      status: "approved",
      center: { type: "Point", coordinates: [13.8189036, 47.8984693] },
      radius_meters: 25,
      comparison_margin_meters: 25,
      effective_comparison_radius_meters: 50,
      visibility: "scim_active",
      operator_note: "icon: Restaurant | label: Grünbergalm",
      approved_by: "osm_extract_2026-05-25",
      approved_at: "2026-05-25T00:00:00.000Z",
      system_adjust_version: "sys_v1.0.0",
    },
    {
      poi_id: "poi_009",
      source_poi_id: "way/386752559",
      source: "osm",
      name: "Sommerrodelbahn Grünberg-Flitzer",
      category: "manual_other",
      candidate_class: "safe_relevant",
      status: "approved",
      center: { type: "Point", coordinates: [13.8201916, 47.8985163] },
      radius_meters: 30,
      comparison_margin_meters: 25,
      effective_comparison_radius_meters: 55,
      visibility: "scim_active",
      operator_note: "icon: Hochschaubahn | label: Sommerrodeln | subtype: alpine_coaster",
      approved_by: "osm_extract_2026-05-25",
      approved_at: "2026-05-25T00:00:00.000Z",
      system_adjust_version: "sys_v1.0.0",
    },
    {
      poi_id: "poi_010",
      source_poi_id: "node/5797937754",
      source: "osm",
      name: "Baumwipfelpfad Salzkammergut",
      category: "manual_other",
      candidate_class: "safe_relevant",
      status: "approved",
      center: { type: "Point", coordinates: [13.8181630, 47.8981683] },
      radius_meters: 30,
      comparison_margin_meters: 25,
      effective_comparison_radius_meters: 55,
      visibility: "scim_active",
      operator_note: "icon: Holzbrücke | label: Wipfelpfad | subtype: treetop_walk",
      approved_by: "osm_extract_2026-05-25",
      approved_at: "2026-05-25T00:00:00.000Z",
      system_adjust_version: "sys_v1.0.0",
    },
    {
      poi_id: "poi_011",
      source_poi_id: "way/755755991",
      source: "osm",
      name: "Paragleiter-Startplatz Grünberg",
      category: "manual_other",
      candidate_class: "safe_relevant",
      status: "approved",
      center: { type: "Point", coordinates: [13.8180351, 47.8984179] },
      radius_meters: 40,
      comparison_margin_meters: 25,
      effective_comparison_radius_meters: 65,
      visibility: "scim_active",
      operator_note: "icon: Paragleiter | label: Startplatz | subtype: paragliding_takeoff",
      approved_by: "osm_extract_2026-05-25",
      approved_at: "2026-05-25T00:00:00.000Z",
      system_adjust_version: "sys_v1.0.0",
    },
    {
      poi_id: "poi_012",
      source_poi_id: "node/911877804",
      source: "osm",
      name: "Adlerhorst (Klettergarten)",
      category: "manual_other",
      candidate_class: "safe_relevant",
      status: "approved",
      center: { type: "Point", coordinates: [13.8191708, 47.8803148] },
      radius_meters: 40,
      comparison_margin_meters: 25,
      effective_comparison_radius_meters: 65,
      visibility: "scim_active",
      operator_note: "icon: Karabiner | label: Adlerhorst | subtype: climbing",
      approved_by: "osm_extract_2026-05-25",
      approved_at: "2026-05-25T00:00:00.000Z",
      system_adjust_version: "sys_v1.0.0",
    },
    {
      poi_id: "poi_013",
      source_poi_id: "way/704671635",
      source: "osm",
      name: "BSV Salzkammergut (3D-Bogenparcours)",
      category: "manual_other",
      candidate_class: "safe_relevant",
      status: "approved",
      center: { type: "Point", coordinates: [13.8115432, 47.8815527] },
      radius_meters: 50,
      comparison_margin_meters: 25,
      effective_comparison_radius_meters: 75,
      visibility: "scim_active",
      operator_note: "icon: Bogen | label: Parcour | subtype: archery",
      approved_by: "osm_extract_2026-05-25",
      approved_at: "2026-05-25T00:00:00.000Z",
      system_adjust_version: "sys_v1.0.0",
    },
    {
      poi_id: "poi_014",
      source_poi_id: "way/386752557+website/niederseilgarten",
      source: "osm",
      name: "Abenteuerspielplatz (mit Niederseilgarten)",
      category: "manual_other",
      candidate_class: "safe_relevant",
      status: "approved",
      center: { type: "Point", coordinates: [13.8194789, 47.8982227] },
      radius_meters: 30,
      comparison_margin_meters: 25,
      effective_comparison_radius_meters: 55,
      visibility: "scim_active",
      operator_note: "icon: Spielplatz | label: Abenteuer | subtype: playground",
      approved_by: "osm_extract_2026-05-25",
      approved_at: "2026-05-25T00:00:00.000Z",
      system_adjust_version: "sys_v1.0.0",
    },
    {
      poi_id: "poi_015",
      source_poi_id: "way/1095296673",
      source: "osm",
      name: "See Loungerie",
      category: "cafe",
      candidate_class: "safe_relevant",
      status: "approved",
      center: { type: "Point", coordinates: [13.8069052, 47.9136127] },
      radius_meters: 25,
      comparison_margin_meters: 25,
      effective_comparison_radius_meters: 50,
      visibility: "scim_active",
      operator_note: "icon: Getränk | label: Lounge | subtype: bar",
      approved_by: "osm_extract_2026-05-25",
      approved_at: "2026-05-25T00:00:00.000Z",
      system_adjust_version: "sys_v1.0.0",
    },
    {
      poi_id: "poi_016",
      source_poi_id: "node/403901524",
      source: "osm",
      name: "Katzenstein",
      category: "peak",
      candidate_class: "safe_relevant",
      status: "approved",
      center: { type: "Point", coordinates: [13.8592910, 47.8745443] },
      radius_meters: 30,
      comparison_margin_meters: 25,
      effective_comparison_radius_meters: 55,
      visibility: "scim_active",
      operator_note: "icon: Gipfelkreuz | label: Katzenstein 1349 m",
      approved_by: "osm_extract_2026-05-25",
      approved_at: "2026-05-25T00:00:00.000Z",
      system_adjust_version: "sys_v1.0.0",
    },
    {
      poi_id: "poi_017",
      source_poi_id: "node/peak/freundschaftshoehe",
      source: "osm",
      name: "Freundschaftshöhe",
      category: "peak",
      candidate_class: "safe_relevant",
      status: "approved",
      center: { type: "Point", coordinates: [13.8394690, 47.8808623] },
      radius_meters: 30,
      comparison_margin_meters: 25,
      effective_comparison_radius_meters: 55,
      visibility: "scim_active",
      operator_note: "icon: Gipfelkreuz | label: Freundschaftshöhe 1020 m",
      approved_by: "osm_extract_2026-05-25",
      approved_at: "2026-05-25T00:00:00.000Z",
      system_adjust_version: "sys_v1.0.0",
    },
    {
      poi_id: "poi_018",
      source_poi_id: "node/peak/gruenberg",
      source: "osm",
      name: "Grünberg",
      category: "peak",
      candidate_class: "safe_relevant",
      status: "approved",
      center: { type: "Point", coordinates: [13.8195778, 47.8983989] },
      radius_meters: 30,
      comparison_margin_meters: 25,
      effective_comparison_radius_meters: 55,
      visibility: "scim_active",
      operator_note: "icon: Gipfelkreuz | label: Grünberg 986 m",
      approved_by: "osm_extract_2026-05-25",
      approved_at: "2026-05-25T00:00:00.000Z",
      system_adjust_version: "sys_v1.0.0",
    },
    {
      poi_id: "poi_019",
      source_poi_id: "node/peak/hochgschirr",
      source: "osm",
      name: "Hochgschirr",
      category: "peak",
      candidate_class: "safe_relevant",
      status: "approved",
      center: { type: "Point", coordinates: [13.8307506, 47.8963537] },
      radius_meters: 30,
      comparison_margin_meters: 25,
      effective_comparison_radius_meters: 55,
      visibility: "scim_active",
      operator_note: "icon: Gipfelkreuz | label: Hochgschirr 981 m",
      approved_by: "osm_extract_2026-05-25",
      approved_at: "2026-05-25T00:00:00.000Z",
      system_adjust_version: "sys_v1.0.0",
    },
    {
      poi_id: "poi_020",
      source_poi_id: "node/peak/duerrenberg",
      source: "osm",
      name: "Dürrenberg",
      category: "peak",
      candidate_class: "safe_relevant",
      status: "approved",
      center: { type: "Point", coordinates: [13.8189124, 47.8893456] },
      radius_meters: 30,
      comparison_margin_meters: 25,
      effective_comparison_radius_meters: 55,
      visibility: "scim_active",
      operator_note: "icon: Gipfelkreuz | label: Dürrenberg 687 m",
      approved_by: "osm_extract_2026-05-25",
      approved_at: "2026-05-25T00:00:00.000Z",
      system_adjust_version: "sys_v1.0.0",
    },
    {
      poi_id: "poi_021",
      source_poi_id: "node/peak/schlosskogel",
      source: "osm",
      name: "Schlosskogel",
      category: "peak",
      candidate_class: "safe_relevant",
      status: "approved",
      center: { type: "Point", coordinates: [13.8187328, 47.8794980] },
      radius_meters: 30,
      comparison_margin_meters: 25,
      effective_comparison_radius_meters: 55,
      visibility: "scim_active",
      operator_note: "icon: Gipfelkreuz | label: Schlosskogel 649 m",
      approved_by: "osm_extract_2026-05-25",
      approved_at: "2026-05-25T00:00:00.000Z",
      system_adjust_version: "sys_v1.0.0",
    },
    {
      poi_id: "poi_022",
      source_poi_id: "node/peak/adlerhorst",
      source: "osm",
      name: "Adlerhorst",
      category: "peak",
      candidate_class: "safe_relevant",
      status: "approved",
      center: { type: "Point", coordinates: [13.8197051, 47.8808177] },
      radius_meters: 30,
      comparison_margin_meters: 25,
      effective_comparison_radius_meters: 55,
      visibility: "scim_active",
      operator_note: "icon: Gipfelkreuz | label: Adlerhorst",
      approved_by: "osm_extract_2026-05-25",
      approved_at: "2026-05-25T00:00:00.000Z",
      system_adjust_version: "sys_v1.0.0",
    },
    {
      poi_id: "poi_023",
      source_poi_id: "node/peak/kleiner_adlerhorst",
      source: "osm",
      name: "Kleiner Adlerhorst",
      category: "peak",
      candidate_class: "safe_relevant",
      status: "approved",
      center: { type: "Point", coordinates: [13.8199787, 47.8807911] },
      radius_meters: 30,
      comparison_margin_meters: 25,
      effective_comparison_radius_meters: 55,
      visibility: "scim_active",
      operator_note: "icon: Gipfelkreuz | label: Kleiner Adlerhorst",
      approved_by: "osm_extract_2026-05-25",
      approved_at: "2026-05-25T00:00:00.000Z",
      system_adjust_version: "sys_v1.0.0",
    },
    {
      poi_id: "poi_024",
      source_poi_id: "node/vp/traunseeblick",
      source: "osm",
      name: "Traunseeblick",
      category: "viewpoint",
      candidate_class: "safe_relevant",
      status: "approved",
      center: { type: "Point", coordinates: [13.8302855, 47.8956487] },
      radius_meters: 25,
      comparison_margin_meters: 25,
      effective_comparison_radius_meters: 50,
      visibility: "scim_active",
      operator_note: "icon: Fernglas | label: Traunseeblick",
      approved_by: "osm_extract_2026-05-25",
      approved_at: "2026-05-25T00:00:00.000Z",
      system_adjust_version: "sys_v1.0.0",
    },
    {
      poi_id: "poi_025",
      source_poi_id: "node/4209056839",
      source: "osm",
      name: "Überraschung",
      category: "viewpoint",
      candidate_class: "safe_relevant",
      status: "approved",
      center: { type: "Point", coordinates: [13.8223568, 47.8797526] },
      radius_meters: 25,
      comparison_margin_meters: 25,
      effective_comparison_radius_meters: 50,
      visibility: "scim_active",
      operator_note: "icon: Fernglas | label: Überraschung 789 m",
      approved_by: "osm_extract_2026-05-25",
      approved_at: "2026-05-25T00:00:00.000Z",
      system_adjust_version: "sys_v1.0.0",
    },
    {
      poi_id: "poi_026",
      source_poi_id: "node/vp/hochgschirr_anstieg",
      source: "osm",
      name: "(Hochgschirr-Anstieg)",
      category: "viewpoint",
      candidate_class: "safe_relevant",
      status: "approved",
      center: { type: "Point", coordinates: [13.8275961, 47.8973377] },
      radius_meters: 25,
      comparison_margin_meters: 25,
      effective_comparison_radius_meters: 50,
      visibility: "scim_active",
      operator_note: "icon: Fernglas | label: Hochgschirr-Anstieg",
      approved_by: "osm_extract_2026-05-25",
      approved_at: "2026-05-25T00:00:00.000Z",
      system_adjust_version: "sys_v1.0.0",
    },
    {
      poi_id: "poi_027",
      source_poi_id: "node/vp/duerrenberg_aussicht",
      source: "osm",
      name: "(Dürrenberg-Aussicht)",
      category: "viewpoint",
      candidate_class: "safe_relevant",
      status: "approved",
      center: { type: "Point", coordinates: [13.8166863, 47.8893630] },
      radius_meters: 25,
      comparison_margin_meters: 25,
      effective_comparison_radius_meters: 50,
      visibility: "scim_active",
      operator_note: "icon: Fernglas | label: Dürrenberg-Aussicht",
      approved_by: "osm_extract_2026-05-25",
      approved_at: "2026-05-25T00:00:00.000Z",
      system_adjust_version: "sys_v1.0.0",
    },
    {
      poi_id: "poi_028",
      source_poi_id: "node/4210998104",
      source: "osm",
      name: "(Westhang)",
      category: "picnic_site",
      candidate_class: "safe_relevant",
      status: "approved",
      center: { type: "Point", coordinates: [13.8070759, 47.9029581] },
      radius_meters: 15,
      comparison_margin_meters: 25,
      effective_comparison_radius_meters: 40,
      visibility: "scim_active",
      operator_note: "icon: Tisch | label: Westhang",
      approved_by: "osm_extract_2026-05-25",
      approved_at: "2026-05-25T00:00:00.000Z",
      system_adjust_version: "sys_v1.0.0",
    },
    {
      poi_id: "poi_029",
      source_poi_id: "merge/13811177439+440+441",
      source: "osm",
      name: "(Hochweg, 3 Tische gemittelt)",
      category: "picnic_site",
      candidate_class: "safe_relevant",
      status: "approved",
      center: { type: "Point", coordinates: [13.8083321, 47.9079715] },
      radius_meters: 20,
      comparison_margin_meters: 25,
      effective_comparison_radius_meters: 45,
      visibility: "scim_active",
      operator_note: "icon: Tisch | label: Hochweg",
      approved_by: "osm_extract_2026-05-25",
      approved_at: "2026-05-25T00:00:00.000Z",
      system_adjust_version: "sys_v1.0.0",
    },
    {
      poi_id: "poi_030",
      source_poi_id: "node/1222222168",
      source: "osm",
      name: "Holzknecht Unterstand",
      category: "shelter",
      candidate_class: "safe_relevant",
      status: "approved",
      center: { type: "Point", coordinates: [13.8379059, 47.8899705] },
      radius_meters: 15,
      comparison_margin_meters: 25,
      effective_comparison_radius_meters: 40,
      visibility: "scim_active",
      operator_note: "icon: Tisch mit Dach | label: Holzknecht",
      approved_by: "osm_extract_2026-05-25",
      approved_at: "2026-05-25T00:00:00.000Z",
      system_adjust_version: "sys_v1.0.0",
    },
    {
      poi_id: "poi_031",
      source_poi_id: "node/water/laudachsee",
      source: "osm",
      name: "Laudachsee",
      category: "manual_other",
      candidate_class: "safe_relevant",
      status: "approved",
      center: { type: "Point", coordinates: [13.8533433, 47.8791353] },
      radius_meters: 50,
      comparison_margin_meters: 25,
      effective_comparison_radius_meters: 75,
      visibility: "scim_active",
      operator_note: "icon: Wasser | label: Laudachsee | subtype: water",
      approved_by: "osm_extract_2026-05-25",
      approved_at: "2026-05-25T00:00:00.000Z",
      system_adjust_version: "sys_v1.0.0",
    },
  ],
  rejected_pois: [],
  pending_pois: [],
  poi_radii: [],
  regional_parameters: {
    parameter_version: 'regio_params_v1.0.0',
    comparison_margin_meters: 25,
    stay_density_ratio: 1.6,
    movement_load_threshold: 0.7,
    stay_load_threshold: 0.7,
    route_degrade_threshold: 0.65,
    route_exclude_threshold: 0.9,
    route_exceedance_behavior: 'degrade',
    signal_validity_seconds: 300,
    aggregation_window_seconds: 300,
    smoothing_strength: 0.35,
    edge_weight_factor: 1.0,
    fallback_route_policy: 'allow_degraded_if_no_alternative',
    route_profiles: [
      {
        profile_id: 'low_load_route',
        label: 'Auslastungsarme Route',
        movement_load_threshold: 0.55,
        stay_load_threshold: 0.55,
        route_degrade_threshold: 0.5,
        route_exclude_threshold: 0.85,
        route_exceedance_behavior: 'profile_dependent',
        enabled: true,
      },
    ],
    system_adjust_version: 'sys_v1.0.0',
  },
  regional_restrictions: [],
  regional_warnings: [],
  release: {
    release_status: 'draft',
    release_id: 'regio_release_gruenberg_draft',
    changelog: 'Update 2026-05-25: 31 POIs nach Reinigung + gruenberg.info-Querprüfung.',
    blocks_runtime_use: false,
  },
  validation: {
    is_valid: true,
    errors: [],
    warnings: [],
    checked_at: '2026-05-25T00:00:00.000Z',
    checked_against_system_adjust_version: 'sys_v1.0.0',
  },
  status: 'regio_content_valid',
};
