import type { TelcoLoadState } from './telcoLoad.types';

export const mockTelcoLoadState: TelcoLoadState = {
  telco_load_batch_id: 'load_001',
  source: 'mock',
  loaded_at: '2026-05-21T00:00:00.000Z',
  provider: {
    provider_id: 'mock_telco',
    provider_name: 'Mock Telco Provider',
    data_contract_version: '1.0.0',
    anonymization_method: 'pre_aggregated',
    raw_signal_access: false,
    device_level_access: false,
  },
  short_interval_window_seconds: 10,
  short_interval_enabled: false,
  time_window: {
    start_at: '2026-05-21T09:00:00.000Z',
    end_at: '2026-05-21T09:05:00.000Z',
    duration_seconds: 300,
    aggregation_window_seconds: 300,
    generated_at: '2026-05-21T09:05:30.000Z',
    timezone: 'Europe/Vienna',
  },
  spatial_scope: {
    scope_id: 'scope_hochwab_nord',
    scope_type: 'region',
    bbox: [15.0, 47.5, 15.4, 47.8],
    spatial_resolution_meters: 25,
    projection_method: 'cell_to_area',
    related_region_id: 'reg_hochwab_nord',
  },
  load_signals: [
    {
      signal_group_id: 'sg_001',
      signal_type: 'runtime_load',
      aggregation_unit: 'area_bucket',
      approximate_center: { type: 'Point', coordinates: [15.214, 47.642] },
      time_window: {
        start_at: '2026-05-21T09:00:00.000Z',
        end_at: '2026-05-21T09:05:00.000Z',
        duration_seconds: 300,
        aggregation_window_seconds: 300,
        generated_at: '2026-05-21T09:05:30.000Z',
        timezone: 'Europe/Vienna',
      },
      metrics: {
        signal_count: 18,
        distinct_device_count: 7,
        density_score: 0.62,
        normalized_load_score: 0.58,
        movement_ratio: 0.74,
        stillness_ratio: 0.26,
        confidence_score: 0.82,
        sample_duration_seconds: 300,
      },
      quality: {
        quality_level: 'high',
        confidence_score: 0.82,
        spatial_accuracy_level: 'medium',
        temporal_accuracy_level: 'high',
        aggregation_completeness: 'complete',
        has_conflicts: false,
      },
      privacy: {
        aggregation_verified: true,
        meets_min_distinct_devices: true,
        meets_min_signal_count: true,
        single_device_visibility_possible: false,
        raw_signal_payload_present: false,
        device_ids_present: false,
        exact_trace_present: false,
        sensus_core_safe: true,
      },
      validity: {
        validity_status: 'valid',
        valid_until: '2026-05-21T09:10:00.000Z',
        age_seconds: 30,
        decay_factor: 1,
        expired: false,
        stale: false,
        usable_for_runtime: true,
      },
      intended_use: ['movement_load_input', 'route_relevance_input'],
    },
    {
      signal_group_id: 'sg_002',
      signal_type: 'stillness_indicator',
      aggregation_unit: 'poi_radius_candidate',
      approximate_center: { type: 'Point', coordinates: [15.225, 47.651] },
      time_window: {
        start_at: '2026-05-21T09:00:00.000Z',
        end_at: '2026-05-21T09:05:00.000Z',
        duration_seconds: 300,
        aggregation_window_seconds: 300,
        generated_at: '2026-05-21T09:05:30.000Z',
        timezone: 'Europe/Vienna',
      },
      metrics: {
        signal_count: 24,
        distinct_device_count: 9,
        density_score: 0.77,
        normalized_load_score: 0.71,
        movement_ratio: 0.18,
        stillness_ratio: 0.82,
        confidence_score: 0.86,
        sample_duration_seconds: 300,
      },
      quality: {
        quality_level: 'high',
        confidence_score: 0.86,
        spatial_accuracy_level: 'medium',
        temporal_accuracy_level: 'high',
        aggregation_completeness: 'complete',
        has_conflicts: false,
      },
      privacy: {
        aggregation_verified: true,
        meets_min_distinct_devices: true,
        meets_min_signal_count: true,
        single_device_visibility_possible: false,
        raw_signal_payload_present: false,
        device_ids_present: false,
        exact_trace_present: false,
        sensus_core_safe: true,
      },
      validity: {
        validity_status: 'valid',
        valid_until: '2026-05-21T09:10:00.000Z',
        age_seconds: 30,
        decay_factor: 1,
        expired: false,
        stale: false,
        usable_for_runtime: true,
      },
      intended_use: ['stay_classification_input'],
    },
  ],
  aggregation_level: {
    aggregation_level_id: 'agg_001',
    aggregation_type: 'provider_pre_aggregated',
    min_distinct_devices_observed: 7,
    min_signal_count_observed: 18,
    aggregation_window_seconds: 300,
    spatial_resolution_meters: 25,
    stable_aggregate_duration_seconds: 300,
    pre_aggregated_by_provider: true,
  },
  signal_quality: {
    overall_quality: 'high',
    valid_group_count: 2,
    warning_group_count: 0,
    invalid_group_count: 0,
    expired_group_count: 0,
    privacy_blocked_group_count: 0,
    conflict_group_count: 0,
  },
  expiry_rules: {
    max_validity_seconds: 300,
    decay_supported: true,
    decay_half_life_seconds: 300,
    expired_group_behavior: 'exclude',
    stale_group_behavior: 'apply_decay',
  },
  privacy_check: {
    is_privacy_valid: true,
    checked_against_system_adjust_version: 'sys_v1.0.0',
    blocked_group_ids: [],
    warning_group_ids: [],
    raw_payload_detected: false,
    device_level_data_detected: false,
    exact_trace_detected: false,
    notes: [],
  },
  validation: {
    is_valid: true,
    errors: [],
    warnings: [],
    checked_at: '2026-05-21T00:00:00.000Z',
    checked_against_system_adjust_version: 'sys_v1.0.0',
    checked_against_regio_content_version: 'regio_v1.0.0',
    checked_against_target_app_ui_version: 'ui_v1.0.0',
  },
  status: 'telco_load_valid',
};
