import type { SystemAdjustState } from './systemAdjust.types';

export const mockSystemAdjustState: SystemAdjustState = {
  system_adjust_version: 'sys_v1.0.0',
  source: 'mock',
  loaded_at: '2026-05-21T00:00:00.000Z',
  privacy_limits: {
    min_distinct_devices_per_visible_aggregate: 5,
    min_signals_per_visible_aggregate: 15,
    min_signals_per_route_relevance: 10,
    min_signals_for_stay_classification: 10,
    min_signals_for_movement_load: 8,
    min_aggregation_window_seconds: 60,
    max_raw_signal_validity_seconds: 300,
    max_raw_signal_storage_seconds: 300,
    max_aggregated_signal_storage_seconds: 7776000,
    spatial_min_resolution_meters: 10,
    min_visible_edge_length_meters: 100,
    min_visible_stay_area_radius_meters: 30,
    allow_single_device_visibility: false,
    allow_raw_signals_in_operator_ui: false,
    allow_raw_signals_in_sensus_core: false,
    allow_debug_data_in_sensus_core: false,
  },
  aggregation_limits: {
    min_time_window_seconds: 60,
    max_time_window_seconds: 1800,
    default_time_window_seconds: 900,
    min_distinct_devices: 5,
    min_signal_count: 15,
    min_stable_aggregate_duration_seconds: 120,
    decay_supported: true,
    default_decay_half_life_seconds: 450,
  },
  allowed_ranges: {
    poi_radius_meters: { min: 5, max: 500, step: 5, unit: 'm' },
    comparison_margin_meters: { min: 0, max: 100, step: 5, unit: 'm' },
    boundary_buffer_meters: { min: 150, max: 500, step: 10, unit: 'm' },
    stay_density_ratio: { min: 1.0, max: 5.0, step: 0.1, unit: 'ratio' },
    movement_load_threshold: { min: 0, max: 1, step: 0.01, unit: 'score' },
    stay_load_threshold: { min: 0, max: 1, step: 0.01, unit: 'score' },
    route_degrade_threshold: { min: 0, max: 1, step: 0.01, unit: 'score' },
    route_exclude_threshold: { min: 0, max: 1, step: 0.01, unit: 'score' },
    signal_validity_seconds: { min: 30, max: 3600, step: 30, unit: 's' },
    smoothing_strength: { min: 0, max: 1, step: 0.05, unit: 'score' },
    edge_weight_factor: { min: 0, max: 10, step: 0.1, unit: 'factor' },
    density_threshold_persons_per_sqm: { min: 0.1, max: 10, step: 0.1, unit: 'p/m²' },
    measurement_interval_seconds: { min: 1, max: 60, step: 1, unit: 's' },
    slowdown_threshold_ratio: { min: 0.1, max: 1.0, step: 0.05, unit: 'ratio' },
    standstill_threshold_ms: { min: 0.05, max: 2.0, step: 0.05, unit: 'm/s' },
    min_standstill_duration_seconds: { min: 5, max: 300, step: 5, unit: 's' },
    min_throughput_ratio_for_rast: { min: 0.1, max: 1.0, step: 0.05, unit: 'ratio' },
    min_compactness_ratio: { min: 0.1, max: 1.0, step: 0.05, unit: 'ratio' },
    min_observation_window_seconds: { min: 60, max: 3600, step: 60, unit: 's' },
    max_jam_throughput_ratio: { min: 0, max: 0.5, step: 0.05, unit: 'ratio' },
  },
  default_parameters: {
    default_poi_radius_meters: 50,
    default_comparison_margin_meters: 25,
    default_stay_density_ratio: 1.6,
    default_movement_load_threshold: 0.7,
    default_stay_load_threshold: 0.7,
    default_route_degrade_threshold: 0.65,
    default_route_exclude_threshold: 0.9,
    default_signal_validity_seconds: 900,
    default_decay_half_life_seconds: 450,
    default_smoothing_strength: 0.35,
    default_edge_weight_factor: 1.0,
    route_exceedance_default_behavior: 'degrade',
    default_density_threshold_persons_per_sqm: 1.0,
    default_measurement_interval_seconds: 10,
    default_slowdown_threshold_ratio: 0.60,
    default_standstill_threshold_ms: 0.3,
    default_min_standstill_duration_seconds: 45,
    default_min_throughput_ratio_for_rast: 0.60,
    default_min_compactness_ratio: 0.4,
    default_min_observation_window_seconds: 300,
    default_max_jam_throughput_ratio: 0.20,
  },
  rule_versions: {
    system_rules: '1.0.0',
    privacy_rules: '1.0.0',
    aggregation_rules: '1.0.0',
    poi_candidate_rules: '1.0.0',
    stay_classification_rules: '1.0.0',
    movement_classification_rules: '1.0.0',
    route_evaluation_rules: '1.0.0',
    layer_reduction_rules: '1.0.0',
    sensus_core_export_rules: '1.0.0',
  },
  feature_flags: {
    enable_poi_candidate_suggestions: true,
    enable_stay_classification: true,
    enable_movement_load: true,
    enable_route_evaluation: true,
    enable_jam_indicators: true,
    enable_leaflet_debug_layers: true,
    enable_sensus_core_export: true,
    enable_local_user_tolerances: true,
    enable_stay_zone_detection: false,
    enable_step2_classification: false,
  },
  validation: {
    is_valid: true,
    errors: [],
    warnings: [],
    checked_at: '2026-05-21T00:00:00.000Z',
  },
  status: 'system_adjust_valid',
};
