import type { TargetAppUiState } from './targetAppUi.types';

export const mockTargetAppUiState: TargetAppUiState = {
  target_app_ui_version: 'target_ui_v1.0.0',
  source: 'mock',
  loaded_at: '2026-05-21T00:00:00.000Z',
  app_profile: {
    profile_id: 'sensus_core_child_public_v1',
    profile_name: 'Sensus Core Child Public Profile',
    app_family: 'sensus_core_child',
    audience: 'public_user',
    default_language: 'de',
    supported_languages: ['de', 'en'],
    map_mode: 'leaflet_view',
    offline_supported: false,
    requires_released_regio_content: true,
    requires_released_system_adjust: true,
  },
  visible_layers: [
    {
      layer_id: 'layer_movement_load_reduced',
      layer_type: 'movement_load',
      label: 'Bewegungsauslastung',
      enabled_by_default: true,
      user_toggle_allowed: true,
      min_zoom: 10,
      max_zoom: 18,
      visibility: 'sensus_core_visible',
      data_class: 'reduced_scim_result',
      reduction_required: true,
      depends_on_feature_flag: 'enable_movement_load',
      requires_regio_release: true,
    },
    {
      layer_id: 'layer_stay_density_reduced',
      layer_type: 'stay_density',
      label: 'Aufenthaltsdichte',
      enabled_by_default: true,
      user_toggle_allowed: true,
      min_zoom: 12,
      max_zoom: 18,
      visibility: 'sensus_core_visible',
      data_class: 'reduced_scim_result',
      reduction_required: true,
      depends_on_feature_flag: 'enable_stay_classification',
      requires_regio_release: true,
    },
    {
      layer_id: 'layer_route_options',
      layer_type: 'route_options',
      label: 'Routenvorschläge',
      enabled_by_default: true,
      user_toggle_allowed: false,
      visibility: 'sensus_core_visible',
      data_class: 'reduced_scim_result',
      reduction_required: true,
      depends_on_feature_flag: 'enable_route_evaluation',
      requires_regio_release: true,
    },
    {
      layer_id: 'layer_debug_graph',
      layer_type: 'debug_graph',
      label: 'Debug Graph',
      enabled_by_default: false,
      user_toggle_allowed: false,
      visibility: 'debug_only',
      data_class: 'debug',
      reduction_required: false,
      depends_on_feature_flag: 'enable_leaflet_debug_layers',
      requires_regio_release: false,
    },
  ],
  available_route_modes: [
    {
      route_mode_id: 'balanced_route',
      label: 'Ausgewogene Route',
      description: 'Kombiniert klassische Routenmetriken mit SCIM-Auslastung.',
      enabled: true,
      default_selected: true,
      route_priority: 'balanced',
      allowed_exceedance_behavior: ['warn', 'degrade'],
      user_selectable: true,
    },
    {
      route_mode_id: 'low_load_route',
      label: 'Auslastungsarme Route',
      description: 'Bevorzugt Abschnitte mit geringerer Bewegungsauslastung und niedriger Aufenthaltsbelastung.',
      enabled: true,
      default_selected: false,
      route_priority: 'low_load',
      allowed_exceedance_behavior: ['degrade', 'profile_dependent'],
      user_selectable: true,
      depends_on_regional_profile_id: 'low_load_route',
    },
  ],
  allowed_user_controls: [
    {
      control_id: 'control_route_mode',
      control_type: 'route_mode_select',
      label: 'Routentyp',
      enabled: true,
      default_value: 'balanced_route',
      affects: ['route_filtering', 'route_sorting'],
      local_only: true,
    },
    {
      control_id: 'control_movement_tolerance',
      control_type: 'movement_tolerance_slider',
      label: 'Auslastungstoleranz',
      enabled: true,
      default_value: 0.7,
      min_value: 0,
      max_value: 1,
      step: 0.05,
      unit: 'score',
      system_range_key: 'movement_load_threshold',
      affects: ['route_filtering', 'route_sorting'],
      local_only: true,
    },
    {
      control_id: 'control_display_intensity',
      control_type: 'display_intensity_slider',
      label: 'Darstellungsintensität',
      enabled: true,
      default_value: 0.6,
      min_value: 0,
      max_value: 1,
      step: 0.05,
      unit: 'score',
      system_range_key: 'smoothing_strength',
      affects: ['display_intensity'],
      local_only: true,
    },
  ],
  warning_rules: [
    {
      warning_rule_id: 'warn_degraded_route_section',
      warning_type: 'degraded_route_section',
      enabled: true,
      severity: 'warning',
      trigger: {
        source: 'route_model',
        field: 'route_status',
        operator: 'equals',
        value: 'degraded',
      },
      user_dismissible: true,
      display_mode: 'inline_route_hint',
      message_key: 'route.contains_degraded_sections',
    },
    {
      warning_rule_id: 'warn_no_low_load_alternative',
      warning_type: 'no_low_load_alternative',
      enabled: true,
      severity: 'info',
      trigger: {
        source: 'route_model',
        field: 'low_load_alternative_available',
        operator: 'equals',
        value: false,
      },
      user_dismissible: true,
      display_mode: 'map_badge',
      message_key: 'route.no_low_load_alternative',
    },
  ],
  reduction_profile: {
    profile_id: 'public_reduced_v1',
    remove_raw_signals: true,
    remove_debug_data: true,
    remove_operator_notes: true,
    remove_internal_ids: true,
    aggregate_scores_to_classes: true,
    score_class_count: 5,
    hide_exact_signal_counts: true,
    hide_device_counts: true,
    round_coordinates: true,
    coordinate_precision: 5,
    simplify_geometries: true,
    max_geometry_detail: 'medium',
    allowed_output_data_classes: ['public_aggregate', 'reduced_scim_result'],
  },
  release: {
    release_status: 'released',
    release_id: 'target_ui_release_001',
    released_by: 'operator_mock',
    released_at: '2026-05-21T00:00:00.000Z',
    changelog: 'Initiales Mock-Profil für Sensus Core Child.',
    blocks_runtime_use: false,
  },
  validation: {
    is_valid: true,
    errors: [],
    warnings: [],
    checked_at: '2026-05-21T00:00:00.000Z',
    checked_against_system_adjust_version: 'sys_v1.0.0',
    checked_against_regio_content_version: 'regio_v1.0.0',
  },
  status: 'target_app_ui_valid',
};
